name: CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      # Install Semgrep
      - name: Install Semgrep
        run: pip install semgrep

      # Run Semgrep scan
      - name: Run Semgrep
        run: semgrep --config=auto . > report.txt
      
      - name: Display report
        run: cat report.txt
        
