name: CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      # Install Semgrep
      - name: Install Semgrep
        run: pip install semgrep

      # Run Semgrep scan
      - name: Run Semgrep
        run: semgrep --config=auto . --json --output semgrep-report.json

      # Save the semgrep report
      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v5
        with:
          name: semgrep-report
          path: semgrep-report.json
